---
- name: Install LEMP stack | install NGINX 
  dnf: 
    name: nginx 
    state: latest 

- name: Install LEMP stack | install MariaDB
  dnf: 
    name: 
      - mariadb-server
      - python3-PyMySQL

- name: Install LEMP stack | install PHP-FPM
  dnf: 
    name: 
      - php-fpm
      - php-mysqlnd
    state: latest

- name: Configure LEMP stack | Start and enable MariaDB/NGINX/PHP-FPM
  service: 
    name: "{{ item }}" 
    state: started 
    enabled: true
  loop:
    - mariadb 
    - nginx 
    - php-fpm

- name: Configure LEMP stack | Set a password to the root user for MariaDB
  mysql_user:
    check_implicit_admin: true
    login_user: root 
    login_password: "{{ mariadb_root_pass }}"
    user: root 
    password: "{{ mariadb_root_pass }}"
    host: localhost 


- name: Configure LEMP stack | Changing 'www.conf' user/group = nginx
  lineinfile:
    path: /etc/php-fpm.d/www.conf
    regexp: "^{{ item }} = apache"
    line: "{{ item }} = nginx"
  loop: 
    - user 
    - group

- name: Installing PHP Extensions
  dnf: 
    name: "{{ extensions_php }}"
    state: latest

- name: Configure MariaDB | Create database for Moodle
  mysql_db:
    name: "{{ db_name }}"
    state: present
    login_user: root 
    login_password: "{{ mariadb_root_pass }}"

- name: Configure MariaDB | Create user database for Moodle
  community.mysql.mysql_user:
    name: "{{ db_user_name }}"
    password: "{{ db_user_pass }}"
    priv: '*.*:ALL,GRANT'
    host: '%'
    state: present
    login_user: root
    login_password: "{{ mariadb_root_pass }}"

- name: Downloading "Moodle 3.9" from the official website
  get_url:
    url: "{{ download_moodle }}"
    dest: "{{ path_download_moodle }}"

- name: Unzip the Moodle 
  unarchive:
    src: "{{ path_download_moodle }}/moodle-latest-39.tgz"
    dest: "{{ path_download_moodle }}"
    remote_src: yes

- name: Granting rights to the moodle
  file:
    path: "{{ path_download_moodle }}/moodle"
    state: directory
    recurse: yes
    owner: nginx
    group: nginx 
    mode: "0775"

- name: Creating a directory for Moodle files
  file:
    path: "{{ path_download_moodle }}/moodledata"
    state: directory
    recurse: yes
    group: nginx 
    mode: "0770"

- name: Configure file 'config.php' | Copy template for config.php 
  copy:
    src: "{{ path_download_moodle }}/moodle/config-dist.php"
    dest: "{{ path_download_moodle }}/moodle/config.php"
    remote_src: yes 

- name: Configure file 'config.php' | Editing file 'config.php'
  template:
    src: config.php.j2
    dest: "{{ path_download_moodle }}/moodle/config.php"

- name: Configure NGINX | Create a 'moodle.conf' file for nginx
  template: 
    src: moodle.conf.j2
    dest: "{{ nginx_moodle_conf }}"
  notify: 
    - Start ngix and php-fpm

- name: Configure SELinux | Set httpd_can_network_connect
  command: 
    cmd: setsebool -P httpd_can_network_connect on

- name: Configure SELinux | SELinux allow
  command: 
    cmd: chcon -R --type httpd_sys_rw_content_t {{ path_download_moodle }}

- name: Configure firewalld for http trafic
  firewalld: 
    service: http 
    permanent: yes 
    state: enabled 
  notify: 
    - Restart firewalld

- name: Credentials
  debug:
    msg: 
      - "Open the browser 'http://{{ ansible_ssh_host }}'"
      - "#######################################################"
      - "database ---> '{{ db_name }}'"
      - "user db  ---> '{{ db_user_name }}'"
      - "password ---> '{{ db_user_pass }}'"
      - "#######################################################"